In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
def read_csv(folder_path):
    files = os.listdir(folder_path)
    df_list = []
    for file in files:
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)
        country = file.split('_')[0]
        df['Country'] = country
        df_list.append(df)

    combined_df = pd.concat(df_list, ignore_index = True)
    return combined_df

In [7]:
folder_path = 'C:/Users/ASUS/Desktop/UIUC/spring courses/Is 597 PR Programming/Final Project/Batter_Data'
batter_df = read_csv(folder_path)

In [9]:
batter_df

,last_name,first_name,player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa,Country
0,Freeman,Freddie,518692,47,11.6,55.3,107.0,90.6,93.2,86.3,425,186,396.0,19,41.3,4,8.5,6.3,Australia
1,Betts,Mookie,605141,38,11.1,44.7,108.1,91.8,97.2,85.3,393,190,389.0,18,47.4,4,10.5,6.3,Australia
2,Smith,Will,669257,37,13.7,40.5,110.8,90.0,95.3,84.0,390,191,373.0,17,47.2,3,8.1,6.3,Australia
3,Martinez,J.D.,502110,35,17.7,42.9,111.1,96.0,96.8,95.1,409,191,409.0,21,60.0,6,17.1,10.0,Australia
4,Muncy,Max,571970,26,21.8,34.6,111.1,94.7,100.4,89.2,410,199,389.0,14,53.8,8,30.8,14.5,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Conforto,Michael,624424,25,15.2,36.0,109.6,94.4,95.6,92.5,429,192,413.0,13,52.0,3,12.0,6.0,Venezuela
70,Flores,Wilmer,527038,24,23.7,37.5,102.2,85.6,90.4,84.9,392,205,381.0,6,25.0,1,4.2,2.9,Venezuela
71,Pederson,Joc,592626,21,19.2,33.3,111.7,97.1,100.4,91.4,432,239,418.0,13,61.9,5,23.8,12.5,Venezuela
72,Wade Jr.,LaMonte,664774,21,11.8,42.9,111.5,88.6,94.3,82.5,394,178,394.0,11,52.4,3,14.3,7.0,Venezuela
73,Sabol,Blake,666165,19,16.2,15.8,108.5,92.0,92.8,91.2,434,152,434.0,8,42.1,1,5.3,2.9,Venezuela

In [10]:
batter_df.to_csv('batter.csv', index = False)

In [3]:
folder_path = 'C:/Users/ASUS/Desktop/UIUC/spring courses/Is 597 PR Programming/Final Project/Pitcher_Data'
pitcher_df = read_csv(folder_path)

In [4]:
pitcher_df

,last_name,first_name,player_id,year,pa,bip,ba,est_ba,est_ba_minus_ba_diff,slg,est_slg,est_slg_minus_slg_diff,woba,est_woba,est_woba_minus_woba_diff,era,xera,era_minus_xera_diff,Country
0,Kershaw,Clayton,477132,2023,73,51,0.239,0.250,-0.011,0.418,0.453,-0.035,0.306,0.323,-0.017,3.50,4.33,-0.830,Australia
1,Syndergaard,Noah,592789,2023,70,49,0.273,0.253,0.020,0.515,0.388,0.127,0.355,0.302,0.053,5.63,3.74,1.885,Australia
2,May,Dustin,669160,2023,68,49,0.115,0.221,-0.106,0.164,0.339,-0.175,0.181,0.288,-0.107,1.47,3.38,-1.907,Australia
3,Urías,Julio,628711,2023,66,43,0.210,0.180,0.030,0.306,0.264,0.042,0.242,0.220,0.022,1.50,1.97,-0.470,Australia
4,Grove,Michael,675627,2023,58,39,0.302,0.233,0.069,0.453,0.388,0.065,0.358,0.303,0.055,9.00,3.77,5.230,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Rogers,Tyler,643511,2023,27,18,0.042,0.181,-0.139,0.042,0.240,-0.198,0.089,0.223,-0.134,0.00,2.02,-2.020,Venezuela
99,Brebbia,John,605154,2023,25,15,0.273,0.216,0.057,0.455,0.372,0.083,0.331,0.290,0.041,7.94,3.43,4.511,Venezuela
100,Doval,Camilo,666808,2023,24,13,0.200,0.205,-0.005,0.400,0.342,0.058,0.312,0.296,0.016,3.18,3.58,-0.404,Venezuela
101,Rogers,Taylor,573124,2023,20,13,0.357,0.313,0.044,0.857,0.816,0.041,0.566,0.539,0.027,18.90,16.61,2.290,Venezuela
102,Alexander,Scott,518397,2023,19,15,0.211,0.315,-0.104,0.368,0.548,-0.180,0.247,0.369,-0.122,1.80,5.88,-4.080,Venezuela

In [5]:
pitcher_df.to_csv('pitcher.csv', index = False)